### ISSUE TITLE
Better error msg if copr is not availalble

### ISSUE THREAD

**Issue by mluscon** [rpm-software-management/ci-dnf-stack#148]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 170, in _run_module_as_main
  "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/lib/jenkins/workspace/dnf-build/rpm-gitoverlay/rgo/__main__.py", line 116, in <module>
    main()
  File "/var/lib/jenkins/workspace/dnf-build/rpm-gitoverlay/rgo/__main__.py", line 104, in main
    builder = CoprBuilder(args.owner, args.project, args.chroot or ovl.chroot)
  File "/var/lib/jenkins/workspace/dnf-build/rpm-gitoverlay/rgo/builders/copr.py", line 54, in __init__
    build_enable_net=self.enable_net)
  File "/usr/lib/python3.5/site-packages/copr/client_v2/handlers.py", line 357, in create
    response = self.nc.request(url, method="post", data=request_data, do_auth=True)
  File "/usr/lib/python3.5/site-packages/copr/client_v2/net_client.py", line 172, in request
    raise RequestError("Server error", url, kwargs, response)
copr.client_v2.net_client.RequestError
```

**Comment by ignatenkobrain** [comment]
It should be fixed in python-copr
