### ISSUE TITLE
Failing test should report some useful info

### ISSUE THREAD

**Issue by stepasm** [rpm-software-management/ci-dnf-stack#169]
```python
When I execute "dnf" command "-y remove foo" with "success"  # behave/steps/test_behave.py:95
    Then transaction changes are as follows                                # behave/steps/test_behave.py:149
      | State   | Packages      |
      | removed | foo, foo-libs |
      Traceback (most recent call last):
        File "/usr/lib/python2.7/site-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/usr/lib/python2.7/site-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "behave/steps/test_behave.py", line 164, in then_transaction_changes
          removed_packages.remove(candidate)
      ValueError: list.remove(x): x not in list
```

**Comment by ignatenkobrain** [comment]
Fixed as part of #176
