### ISSUE TITLE
shell-5 is still failing

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/ci-dnf-stack#250]
```
type object 'EOF' has no attribute 'group'
```

**Comment by ignatenkobrain** [comment]
```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/behave/model.py", line 1456, in run
    match.run(runner.context)
  File "/usr/lib/python2.7/site-packages/behave/model.py", line 1903, in run
    self.func(context, *args, **kwargs)
  File "behave/steps/shell_steps.py", line 31, in step_i_run_dnf_shell_command
    sys.stdout.write("{}{}".format(context.pexpect_session.before, context.pexpect_session.match.group()))
AttributeError: type object 'EOF' has no attribute 'group'
```

**Comment by ignatenkobrain** [comment]
@MichaelMraka looks like you fixed traceback, but it seems just trying to workaround problem, because:

```
Regexp didn't match: u'TestRepoA' not found in ''
```
